[profile.default]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
